services:
  db:
    image: postgres:latest
    container_name: postgres_greenlight
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: greenlight
    ports:
      - "5432:5432"
    volumes:
      - db_greenlight:/var/lib/postgresql/data

volumes:
  db_greenlight:
